name: "Issue Auto Labeling and Assigning"
description: "trigger an action based on issue content"
inputs:
  github-token:
    description: "Github token"
    required: true
  parameters:
    description: "JSON array of keywords to look for and labels and assignees to be set when there's a keyword match"
    required: true
  area-is-keyword:
    description: "Automatically count the area string as a keyword for that area"
    required: false
    default: false
  default-area:
    description: "Labels and assignees to apply when no keywords are detected"
    required: false
  included-labels:
    description: "Only issues which include one of these labels will be triaged"
    required: false
  excluded-labels:
    description: "Issues which include any of these labels will not be triaged"
    required: false
  excluded-expressions:
    description: "Words to exclude from search"
    required: false
  similarity:
    description: "Determines how similar two words can be for similarity to be detected"
    required: false
    default: ".125"
  body-value:
    description: "How much each keyword in issue body is weighted"
    required: false
    default: ".025"

outputs:
  title:
    description: "Title of Issue"
  body:
    description: "Body of Issue"
  labeled:
    description: "\"true\" if labeled otherwise \"false\""
  assigned:
    description: "\"true\" if assigned otherwise \"false\""
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: alert-circle
  color: gray-dark
